import java.util.*

enum class Provincia{
    ALAVA,ALBACETE,ALICANTE,ALMERIA,ASTURIAS,AVILA,BADAJOZ,BARCELONA,BURGOS,CACERES,CADIZ,
    CANTABRIA,CASTELLON,CIUDAD_REAL,CORDOBA,CORUNHA,CUENCA,GERONA,GRANADA,GUADALAJARA,GUIPUZCOA,
    HUELVA,HUESCA,BALEARES,JAEN,LEON,LERIDA,LUGO,MADRID,MALAGA,MURCIA,NAVARRA,OURENSE,PALENCIA,
    LAS_PALMAS,PONTEVEDRA,LA_RIOJA,SALAMANCA,SEGOVIA,SEVILLA,SORIA,TARRAGONA,SANTA_CRUZ,
    TERUEL,TOLEDO,VALENCIA,VALLADOLID,VIZCAYA,ZAMORA,ZARAGOZA
}